### ISSUE TITLE
[BUG] - Login failed - unauthorized (Postgres)

### ISSUE THREAD

**Issue by bigbeka** [clidey/whodb#532]
**Describe the bug**
Upgraded WhoDB to latest version and lost ability to connect 2 Postgres databases.
Both accesses using LAN they are both on the same subnet and can ping each other.

I can connect to both Databases from pgAdmin 4.

I have also double checked the credential.

I had connected both of them successfully before the upgrade.

When attempted to Submit the connection details, the following logs appear (`docker compose logs -f`):

```
whodb-1  | 2025/06/20 09:14:54 [91638c8a7123/51GfdJqzXz-000049] "POST http://xx.0.0.xxx:8086/api/query HTTP/1.1" from xx.0.0.yy:51951 - 200 68B in 228.556µs
```

**To Reproduce**
1. Update to latest release
2. Open the WhoDB WebUI
3. Add new Postgres database
4. Error appears

**Screenshots**
![Image](https://github.com/user-attachments/assets/3ca304d0-1d74-401b-a5dc-0ffedee6575c)

**Desktop (please complete the following information):**
 - OS that WhoDB is running on: LXC - Ubuntu 22.04
 - How you're running WhoDB: Docker compose
 - Browser: Safari
 - Version: Latest

**Comment by bigbeka** [comment]
I had a test Postgres DB running on the localhost where WhoDB runs (Staging), and it can connect to that DB with no problem using LAN as hostname.

The only difference I see in the login process between successful and unsuccessful connections is that unsuccessful DB connections have `-` in username and Database name: username `xx-yyyyy` and database `xx-xx-xxxx`.

Could this be it?

**Comment by modelorona** [comment]
@bigbeka thanks for the issue! I think it might be related to the latest input validation logic. Will fix it this week, sorry for the inconvenience. In the meantime, can you use the previous version 0.56.0?

**Comment by bigbeka** [comment]
@modelorona no need to apologise! Thank YOU for such a great tool! I rolled back to 0.56.0 and it works perfectly!

Many thanks once again! I will update to the next release version when its out :)

**Comment by tuhuynh1011lod** [comment]
Hi, I have the same problem. However, for me it was for connecting to mysql and mariadb. I also can connect from my DBeaver and have the same type of logs like @bigbeka. 

Yeah, but I think your app is incredible and have many potential.

**Comment by modelorona** [comment]
@tuhuynh1011lod interesting, we've not modified the mariadb or mysql logic for connections! Did you recently upgrade the version or modify your password?

They do both use the same logic, so it's possible the underlying library had a change and we updated. If you did upgrade and happen to remember what version of WhoDB you were previously on, that would be helpful in identifying, but if not, no issue :)

I should have some time this week to resolve, have been traveling for work recently!

**Comment by modelorona** [comment]
@bigbeka I've merged the changes into main and will do a new build soon (after some more testing). Will let you know when that's out!

@tuhuynh1011lod since this was originally a postgres issue, I'll close the ticket. The MySQL/MariaDB login code has not been changed for a long time, and we last updated the driver 3 months ago, so I don't see changes that could affect it.

We do have some character escape logic for the password, not sure if you've recently changed it. If you can provide some more information, I can go create a ticket and investigate. Thanks!

**Comment by bigbeka** [comment]
@modelorona thsnk you so much for your hard work! As soon as the new build is out, I’ll test it and report back!

**Comment by bigbeka** [comment]
@modelorona thank you for getting version 0.58.0 built. Login issue has been resolved.

**Comment by Stephan-MC** [comment]
Please i am on the latest version of whoDB and still face this issue 0.58

**Comment by Stephan-MC** [comment]
> Please i am on the latest version of whoDB and still face this issue 0.58

`sudo docker run -it --network=host -p 8080:8080 clidey/whodb` 

the command above fix things for me
